version: "3"
services:
  service_redis:
    restart: always
    #    ports:
    #      - 6379:6379
    image: redis
    container_name: redis
    environment:
      - TZ=Asia/Shanghai
    command: redis-server
    volumes:
      - D:\docker\redis\data:/data  #redis数据挂载到本地
  service_jusicMusicApi:
    image: jumpalang/jusic_music_api:1.7
    environment:
      - QQ=1040927107 #qq号
    container_name: jusicMusicApi
    ports:
      #      - "3000:3000"
      - "3300:3300"
    #      - "3400:3400"
    #      - "8081:8081"
    restart: always
  service_jusicServeHouses:
    container_name: jusicServeHouses
    image: jumpalang/jusic_serve_houses:2.4
    environment:
      - MusicApi=http://jusicMusicApi  #必须与service_jusicMusicApi的container_name一致
      - APIUSER=admin  #api认证接口用户名
      - APIPWD=54288  #api认证接口密码
      - ServerJUrl=https://sc.ftqq.com/SCU64668T909ada7955daadfb64d5e7652b93fb135dad06e659369.send #server酱消息接口，用户@管理员时会通知微信
      - MiniId=wx693312f83f255cf3
      - MiniSecrect=eccc0908c65a4491da6811b3cbe3e986
      - RoleRootPassword=654321
    ports:
      - "8080:8888"
    depends_on:
      - service_redis
      - service_jusicMusicApi
    restart: always